//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashTag.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HashTag.Properties.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashTag.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Application.Environment.
        /// </summary>
        internal static string HashTag_Application_Environment_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Application.Environment.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Application.Name.
        /// </summary>
        internal static string HashTag_Application_Name_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Application.Name.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string HashTag_Config_OutputResolvedConfiguration_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Config.OutputResolvedConfiguration.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Config.OutputResolvedConfiguration.
        /// </summary>
        internal static string HashTag_Config_OutputResolvedConfiguration_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Config.OutputResolvedConfiguration.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string HashTag_Core_IsCaseSensitive_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Core.IsCaseSensitive.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Core.IsCaseSensitive.
        /// </summary>
        internal static string HashTag_Core_IsCaseSensitive_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Core.IsCaseSensitive.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defaultValue.
        /// </summary>
        internal static string HashTag_Core_Setting_DefaultValueSuffix {
            get {
                return ResourceManager.GetString("HashTag.Core.Setting.DefaultValueSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {HashTag.Diagnostics.InternalLog}.
        /// </summary>
        internal static string HashTag_Core_Setting_InternalLog_TraceSourceName {
            get {
                return ResourceManager.GetString("HashTag.Core.Setting.InternalLog.TraceSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirectToKey.
        /// </summary>
        internal static string HashTag_Core_Setting_RedirectToKeyToken {
            get {
                return ResourceManager.GetString("HashTag.Core.Setting.RedirectToKeyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.TraceSourceConnector, %(Company).Core.
        /// </summary>
        internal static string HashTag_Diagnostics_Connector_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.Connector.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.Connector.
        /// </summary>
        internal static string HashTag_Diagnostics_Connector_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.Connector.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string HashTag_Diagnostics_Default_ApplicationLogLevels_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.Default.ApplicationLogLevels.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.Default.ApplicationLogLevels.
        /// </summary>
        internal static string HashTag_Diagnostics_Default_ApplicationLogLevels_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.Default.ApplicationLogLevels.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        internal static string HashTag_Diagnostics_InternalHandlerTimeOutMs_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.InternalHandlerTimeOutMs.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.InternalHandlerTimeOutMs.
        /// </summary>
        internal static string HashTag_Diagnostics_InternalHandlerTimeOutMs_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.InternalHandlerTimeOutMs.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string HashTag_Diagnostics_InternalLogLevels_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.InternalLogLevels.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.InternalLogLevels.
        /// </summary>
        internal static string HashTag_Diagnostics_InternalLogLevels_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.InternalLogLevels.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string HashTag_Diagnostics_LocalLogLevels_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.LocalLogLevels.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.LocalLogLevels.
        /// </summary>
        internal static string HashTag_Diagnostics_LocalLogLevels_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.LocalLogLevels.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HashTag_Diagnostics_LogfilePath_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.LogfilePath.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.LogfilePath.
        /// </summary>
        internal static string HashTag_Diagnostics_LogfilePath_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.LogfilePath.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.
        /// </summary>
        internal static string HashTag_Diagnostics_MessageBufferBlockSize_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.MessageBufferBlockSize.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.MessageBufferBlockSize.
        /// </summary>
        internal static string HashTag_Diagnostics_MessageBufferBlockSize_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.MessageBufferBlockSize.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string HashTag_Diagnostics_MessageBufferIntervalMs_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.MessageBufferIntervalMs.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.MessageBufferIntervalMs.
        /// </summary>
        internal static string HashTag_Diagnostics_MessageBufferIntervalMs_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.MessageBufferIntervalMs.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string HashTag_Diagnostics_MessageBufferWriteTimeoutMs_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.MessageBufferWriteTimeoutMs.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).Diagnostics.MessageBufferWriteTimeoutMs.
        /// </summary>
        internal static string HashTag_Diagnostics_MessageBufferWriteTimeoutMs_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.Diagnostics.MessageBufferWriteTimeoutMs.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashTag.Remote.Client.ConfigProviderRest, HashTag.Remote.Client.
        /// </summary>
        internal static string HashTag_RemoteConfig_ServiceProvider_defaultValue {
            get {
                return ResourceManager.GetString("HashTag.RemoteConfig.ServiceProvider.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).RemoteConfig.ServiceUrl.
        /// </summary>
        internal static string HashTag_RemoteConfig_ServiceUrl_redirectToKey {
            get {
                return ResourceManager.GetString("HashTag.RemoteConfig.ServiceUrl.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoteWins.
        /// </summary>
        internal static string HasthTag_RemoteConfig_Default_MergeOptions_defaultValue {
            get {
                return ResourceManager.GetString("HasthTag.RemoteConfig.Default.MergeOptions.defaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %(Company).RemoteConfig.Default.MergeOptions.
        /// </summary>
        internal static string HasthTag_RemoteConfig_Default_MergeOptions_redirectToKey {
            get {
                return ResourceManager.GetString("HasthTag.RemoteConfig.Default.MergeOptions.redirectToKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create instance of {0} as {1}.
        /// </summary>
        internal static string MSG_Core_Unable_CreateInstance {
            get {
                return ResourceManager.GetString("MSG_Core_Unable_CreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert resolved key &apos;{0}&apos; value &apos;{1} to {2}.
        /// </summary>
        internal static string MSG_CoreConfig_ConversionError {
            get {
                return ResourceManager.GetString("MSG_CoreConfig_ConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $?NOT RESOLVED: {0}?$.
        /// </summary>
        internal static string MSG_CoreConfig_TokenNotFound {
            get {
                return ResourceManager.GetString("MSG_CoreConfig_TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to apply settings for group. {0}.
        /// </summary>
        internal static string MSG_CoreConfig_UnexpectedGroupName {
            get {
                return ResourceManager.GetString("MSG_CoreConfig_UnexpectedGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using remote setting: {0}: {1} as {2}.
        /// </summary>
        internal static string MSG_CoreConfig_UsingRemoteSetting {
            get {
                return ResourceManager.GetString("MSG_CoreConfig_UsingRemoteSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Formatting error ----.
        /// </summary>
        internal static string MSG_Diagnostics_FormattingError {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_FormattingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal logger configured.
        /// </summary>
        internal static string MSG_Diagnostics_Internal_Logger_Configured {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_Internal_Logger_Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in InternalLog: {0}{1}{2}.
        /// </summary>
        internal static string MSG_Diagnostics_InternalLog_Error {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_InternalLog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to acquire write lock after {0} ms.
        /// </summary>
        internal static string MSG_Diagnostics_InternalLog_WriteLock_Error {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_InternalLog_WriteLock_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal logger filtering messages: {0}.
        /// </summary>
        internal static string MSG_Diagnostics_InternalLogger_FilteringMessagesTo {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_InternalLogger_FilteringMessagesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal logger {0} not configured in system.diagnostics/sources.  Building default source.
        /// </summary>
        internal static string MSG_Diagnostics_InternalLogger_TraceNotFound {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_InternalLogger_TraceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local logger configured.
        /// </summary>
        internal static string MSG_Diagnostics_Local_Logger_Configured {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_Local_Logger_Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Log filtering messages: {0}.
        /// </summary>
        internal static string MSG_Diagnostics_LocalLog_Filtering_Messages_ToSwitch {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_LocalLog_Filtering_Messages_ToSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No listeners specified.  Building default listeners.
        /// </summary>
        internal static string MSG_Diagnostics_LocalLog_No_Listeners_Specified {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_LocalLog_No_Listeners_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal logger bound to: {0}.
        /// </summary>
        internal static string MSG_Diagnostics_LocalLogger_BoundToListener {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_LocalLogger_BoundToListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Id:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_ActivityId {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_ActivityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_Application {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_Categories {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_Environment {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Id:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_EventId {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_EventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_Exception {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Message:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_FullMessage {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_FullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_Host {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logger Name:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_LoggerName {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_LoggerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Code:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_MessageCode {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_MessageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_Priority {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_Reference {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity:.
        /// </summary>
        internal static string MSG_Diagnostics_MessageBuilder_Severity {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_MessageBuilder_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        internal static string MSG_Diagnostics_NullText {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_NullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source level not specified.  Using: {0}.
        /// </summary>
        internal static string MSG_Diagnostics_SourceLevelNotFound {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_SourceLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using log connector: {0}.
        /// </summary>
        internal static string MSG_Diagnostics_Using_LogConnector {
            get {
                return ResourceManager.GetString("MSG_Diagnostics_Using_LogConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method may only be executed within the context of an HTTP context.
        /// </summary>
        internal static string MSG_Web_MissingContext {
            get {
                return ResourceManager.GetString("MSG_Web_MissingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (http request not found).
        /// </summary>
        internal static string MSG_Web_Request_NotFound {
            get {
                return ResourceManager.GetString("MSG_Web_Request_NotFound", resourceCulture);
            }
        }
    }
}
