using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HashTag.Logging.Connector.MSSQL
{
    [ComplexType]
    public class dbEventHttpContext
    {
        [Column(TypeName = "varchar", Order = 200), Display(Name = "If available, provides information about the HTTP server variables when event was generated")]
        public string Server { get; set; }

        [Column(TypeName = "varchar", Order = 210), Display(Name = "If available, provides information about the  query variables when event was generated")]
        public string Query { get; set; }

        [Column(TypeName = "varchar", Order = 220), Display(Name = "If available, provides information about the  cookies variables when event was generated")]
        public string Cookies { get; set; }

        [Column(TypeName = "varchar", Order = 230), Display(Name = "If available, provides information about the  form variables when event was generated")]
        public string Form { get; set; }

        [Column(TypeName = "varchar", Order = 240), Display(Name = "If available, provides information about the  header variables when event was generated")]
        public string Header { get; set; }

        [Column(Order = 250), Display(Name = "String equivilant of  Status Code to return to client.  See: s://msdn.microsoft.com/en-us/library/system.web.management.webeventcodes%28v=vs.110%29.aspx")]
        public Nullable<int> WebEventValue { get; set; }

        [Column(Order = 260), Display(Name = "Numeric value for  Status Code")]
        public Nullable<int> StatusValue { get; set; }

        [MaxLength(50), Column(TypeName = "varchar", Order = 270), Display(Name = "String equivilant of  Status Code to return to client")]
        public string StatusCode { get; set; }

        [Column(TypeName = "varchar", Order = 280), Display(Name = "Server side HTML message as generated by .Net application")]
        public string HtmlMessage { get; set; }
    }
}
