// <auto-generated />
namespace HashTag.Logging.Connector.MSSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update1121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update1121));
        
        string IMigrationMetadata.Id
        {
            get { return "201505300321153_update1121"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
